README.md

Currently, the paper is only available on the project website. To prevent other readers from missing it, I’ve added the paper link in the GitHub README."

added the paper link in the GitHub README

---

docs/source/roboverse_learn/reinforcement_learning/humanoidbench_rl.md
metasim/cfg/tasks/humanoidbench/base_cfg.py
metasim/sim/env_wrapper.py
metasim/sim/isaacgym/isaacgym.py
metasim/sim/isaaclab/isaaclab.py
roboverse_learn/humanoidbench_rl/train_sb3.py
roboverse_learn/humanoidbench_rl/wrapper_sb3.py

1. IsaacLab `get_states()` align with `MuJoCo` and `IsaacGym`
2. IsaacGym `set_states` support for only specified `env_ids`
3. Fix bug
1. HumanoidBench decimation = 1
2. Delete `handler.simulate()` in `reset()`
4. Update doc

IsaacGym and IsaacLab Infra Change

---

metasim/cfg/checkers/checkers.py
metasim/cfg/tasks/humanoidbench/base_cfg.py
metasim/cfg/tasks/open6dor/utils/config_gen.py
metasim/utils/humanoid_reward_util.py
metasim/utils/humanoid_robot_util.py
roboverse_learn/algorithms/act/detr/models/detr_vae.py
roboverse_learn/algorithms/diffusion_policy/diffusion_policy/model/common/dict_of_tensor_mixin.py
roboverse_learn/algorithms/diffusion_policy/diffusion_policy/model/common/normalizer.py
roboverse_learn/eval_test_demo.py
roboverse_learn/humanoidbench_rl/wrapper_sb3.py

We speed up humanoidbench to around 30x.
First we make get_state as batched tensor
Then we merge humanoidbench tasks with batch reward, checker and so on.
It speed up training around 30x

HumanoidBench speed up ~30x

---

metasim/cfg/tasks/humanoidbench/base_cfg.py
metasim/sim/base.py
metasim/sim/isaacgym/isaacgym.py
metasim/sim/isaaclab/isaaclab.py
metasim/sim/mujoco/mujoco.py
metasim/utils/humanoid_robot_util.py
metasim/utils/state.py
roboverse_learn/humanoidbench_rl/train_sb3.py
roboverse_learn/humanoidbench_rl/wrapper_sb3.py

Originally PR 108

---

metasim/sim/isaacgym/isaacgym.py
metasim/sim/isaaclab/isaaclab.py
roboverse_learn/humanoidbench_rl/configs/isaacgym.yaml
roboverse_learn/humanoidbench_rl/configs/isaaclab.yaml
roboverse_learn/humanoidbench_rl/configs/mujoco.yaml
roboverse_learn/humanoidbench_rl/train_sb3.py

1. Clean up the code and add three configurations.  
2. Adjust the hyperparameters.  
3. Remove redundant logging code to prevent printing during each `reset`.

Update `humanoidbench` training code

---

metasim/cfg/robots/base_robot_cfg.py
metasim/cfg/robots/kinova_gen3_robotiq_2f85.py
metasim/scripts/random_action_really_pure.py
metasim/sim/isaaclab/env_overwriter.py
metasim/sim/isaaclab/isaaclab.py
metasim/sim/isaaclab/isaaclab_helper.py

Please test using
```
python metasim/scripts/random_action_really_pure.py --robot=KinovaGen3Robotiq2f85
```
Expected results:
https://github.com/user-attachments/assets/930beecb-a922-41c5-a6dc-e8698478f3d3
Download the robot asset [here](https://drive.google.com/file/d/1H4bYdySo6K3oX1hvHPmn7-Pv4W-24SNd/view?usp=sharing) and put it `roboverse_data/robots/kinova_gen3_robotiq_2f85/usd/renew_v1.usd`. Will update the asset to roboverse_data when this PR is ready to merge

kinova + 2f85 random action success

---

metasim/sim/isaaclab/utils/usd_util.py

Isaaclab ShaderFixer also repair opacity_texture

---

metasim/cfg/scenario.py
metasim/sim/isaaclab/utils/usd_util.py
metasim/utils/hf_util.py

This PR restructure the auto-download code into `FileDownloader` to do parallelized downloading, speed up when there are multiple objects in scenario

[refactor] auto download

---

metasim/cfg/robots/base_robot_cfg.py
metasim/cfg/robots/franka_cfg.py
metasim/sim/isaaclab/isaaclab_helper.py

This PR add support for IsaacLab's robots setting actuator stiffness and damping.
After further testing, this PR can be merged

isaaclab support setting actuator stiffness and damping

---

metasim/cfg/objects.py
metasim/cfg/tasks/maniskill/pick_cube_cfg.py
metasim/cfg/tasks/maniskill/stack_cube_cfg.py
metasim/scripts/empty_demo.py

[refactor] remove mjcf_path from PrimitiveCubeCfg

---

Dockerfile

[fix] resolve mamba init command not found in docker

---

Dockerfile

This PR fix docker library conflict by updating LD_LIBRARY_PATH only when metasim_isaacgym conda env is activated
This PR also add section comments for `Dockerfile` for better readability
Fixed #172

[fix] fix docker library conflict

---

docs/source/metasim/get_started/quick_start/0_static_scene.md

Update 0_static_scene.md to use sapien3

---

Dockerfile

[fix] fix genesis non-headless usage in docker

---

Dockerfile

[fix] docker conda init

---

docs/source/roboverse_learn/reinforcement_learning/humanoidbench_rl.md
metasim/cfg/robots/h1_cfg.py
metasim/sim/isaacgym/isaacgym.py

[fix] isaacgym dict access and update docs

---

docs/source/_static/css/custom.css
docs/source/dataset_benchmark/benchmark/overview.md
docs/source/dataset_benchmark/benchmark/results.md
eval.sh
run.sh

FInished BenchMarking and added the results to docs/

RoboVerse Benchmark Update

---

metasim/utils/state.py

[fix] camera state not converted from tensor state to nested state, introduced in #159

---

metasim/sim/mujoco/mujoco.py

[refactor] mujoco simplify code

---

metasim/utils/hf_util.py

[add] mjx autodownload

---

docs/source/metasim/api/metasim/metasim.sim.rst
metasim/sim/base.py
metasim/sim/sapien/__init__.py
metasim/sim/sapien/sapien2.py
metasim/sim/sapien/sapien3.py
metasim/utils/setup_util.py
pyproject.toml

[doc,update] metasim/sim docstrings; update pyproject ruff rules ignore

---

docs/source/metasim/user_guide/support_matrix.rst
metasim/sim/isaacgym/isaacgym.py

[bugfix] isaacgym set joint stiffness=800, damping=40 when not specified

---

metasim/cfg/objects.py
metasim/sim/isaacgym/isaacgym.py
metasim/utils/hf_util.py

As title, add `isaacgym_read_mjcf` option to object cfg.

[feature] isaacgym can read from mjcf file

---

metasim/sim/env_wrapper.py
metasim/sim/mujoco/mujoco.py
metasim/sim/parallel.py
metasim/utils/state.py

[feature] mujoco support parallel envs

---

metasim/sim/isaacgym/isaacgym.py

[fix] isaacgym `dt` definition correct

---

metasim/cfg/checkers/base_checker.py

[fix] specify device in BaseChecker

---

metasim/sim/isaacgym/isaacgym.py
metasim/sim/isaaclab/isaaclab.py

[fix] isaaclab and isaacgym support tensorized action

---

metasim/utils/hf_util.py

As title. This will speed up downloading when network has large latency

[refactor] autodownload check hf exists when local not exists

---

roboverse_learn/algorithms/base_runner.py

[fix] roboverse_learn/eval.py use correct action format

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/proposal.md
.github/ISSUE_TEMPLATE/question.md

The content refers to [Isaac Lab](https://github.com/isaac-sim/IsaacLab), which has done great repo management.

[add] github issue template

---

docs/source/roboverse_learn/reinforcement_learning/skillblender_rl.md

[doc] add skillblender back

---

metasim/sim/isaacgym/isaacgym.py

Still working on it. DO NOT MERGE

Fix IsaacGym Quaternion bugs

---

metasim/scripts/teleop_keyboard.py

[fix] teleop_keyboard.py when using mujoco and states are all on cpu

---

metasim/utils/humanoid_robot_util.py
roboverse_learn/skillblender_rl/env_wrappers/base/humanoid_base_wrapper.py

align humanoid infra with this pr https://github.com/RoboVerseOrg/RoboVerse/pull/277

[fix] align quaternion in humanoid infra

---

docs/source/metasim/developer_guide/data_structure.md
docs/source/metasim/index.md

[doc,update] move hf data structure to developer guide

---

docs/source/metasim/user_guide/real2sim.md

[update] doc for real2sim

---

docs/source/metasim/get_started/advanced/rl_example/1_fttd3_humanoid.md

[doc]fix FastTD3 get_started instructions

---

Dockerfile

Default option is still IsaacLab v1.4.0

[update] dockerfile to allow using isaaclab v2.1.0

---

metasim/sim/mujoco/mujoco.py

mujoco support torque control

---

metasim/cfg/checkers/checkers.py
metasim/cfg/tasks/humanoidbench/slide_cfg.py
roboverse_learn/humanoidbench_rl/configs/mjx.yaml

[fix] humanoid-bench slide task

---

get_started/rl/fast_td3/requirements.txt

update the fast_td3 requirements.txt

update the fast_td3 requirements.txt

---

pyproject.toml

[bugfix] isaaclab v1.4.1 installation bug

---

metasim/sim/mujoco/mujoco.py

Mujoco handler add scale

---

Dockerfile
metasim/sim/sapien/sapien3.py

It has been observed that if IsaacLab is installed in the same Conda environment alongside other simulators, the following error may occur when running IsaacLab:
To resolve this, **creating a separate Conda environment for IsaacLab** is recommended. This approach has been tested and confirmed to work.
**Additional Notes:**
1. MuJoCo can coexist with IsaacLab in the same environment without issues.
2. Potential Unresolved Issues: It is unclear whether this solution might introduce other conflicts. Further verification is advised.

IsaacLab error alongside other simulators

---

metasim/sim/genesis/genesis.py
metasim/types.py

[add]: genesis add torque control

---

docs/source/roboverse_learn/imitation_learning/contributing.md

[fix]: syntax error in imitation learning doc

---

metasim/cfg/robots/robot_template.py

This PR introduces RobotTemplateCfg, a minimal and extensible configuration template for defining new robot models in MetaSim.Includes default fields for joint count, asset paths, physical properties, actuator configs, joint limits, and control types.
Serves as a quick-start reference for integrating new robots into the MetaSim simulation system.
Usage instructions are included in the class docstring to help users adapt this template step by step.

[add]config template for robot config

---

metasim/sim/sapien/sapien2.py
metasim/sim/sapien/sapien3.py

Test new metasim

---

metasim/utils/save_util/save_util_v2.py

Fixed #83 by simply deleting the ee states, since nobody is currently using it

[bugfix] collect demo don't save problemastic ee state

---

pyproject.toml

[update] pyproject: also install roboverse_pack as module

---

roboverse_pack/robots/arx_l5_mjcf_cfg.py
roboverse_pack/robots/gen3_cfg.py
roboverse_pack/robots/iiwa14_cfg.py
roboverse_pack/robots/koch_mjcf_cfg.py
roboverse_pack/robots/lite6_mjcf_cfg.py
roboverse_pack/robots/so_arm100_mjcf_cfg.py
roboverse_pack/robots/ur10e_cfg.py
roboverse_pack/robots/ur5e_cfg.py
roboverse_pack/robots/yam_mjcf_cfg.py
roboverse_pack/robots/z1_cfg.py

[bugfix] robot import error in robot cfgs

---

metasim/sim/parallel.py

Should use "spawn" to create processes instead of "forkserver" on Mac.
Fixes #491
python get_started/3_parallel_envs.py --sim mujoco --headless

Fix ParallelSimWrapper for Mac.

---

metasim/utils/kinematics.py
metasim/utils/teleop_utils.py
roboverse_pack/queries/contact.py
scripts/advanced/teleop_keyboard.py
scripts/advanced/teleop_phone.py
scripts/advanced/teleop_xr.py

[fix] teleop scripts

---

metasim/utils/ik_solver.py
metasim/utils/kinematics.py

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
List any dependencies that are required for this change.
Fixes # (issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update
Please describe how to test the change if applicable.
Please attach before and after screenshots or videos of the change if applicable.

[fix] unstable problem caused by pyroki initial solution

---

docs/source/metasim/get_started/quick_start/8_replay_demo.md
metasim/utils/kinematics.py

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
List any dependencies that are required for this change.
Fixes # (issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update
Please describe how to test the change if applicable.
Please attach before and after screenshots or videos of the change if applicable.

[doc] add replay comment

---

get_started/rl/fast_td3/1_fttd3.py
roboverse_learn/rl/fast_td3/configs/mjx_walk.yaml
roboverse_learn/rl/fast_td3/train.py

[fix] RL evaluate

---

docs/source/metasim/get_started/quick_start/4_motion_planning.md
get_started/4_motion_planning.py
get_started/motion_planning/0_franka_planning.py
get_started/motion_planning/1_object_grasping.py
get_started/motion_planning/2_water_pouring.py
metasim/utils/ik_solver.py
metasim/utils/kinematics.py
roboverse_learn/il/act/act_eval_runner.py
roboverse_learn/il/dp/runner/dp_runner.py
roboverse_learn/vla/vla_eval.py

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
List any dependencies that are required for this change.
Fixes # (issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update
Please describe how to test the change if applicable.
Please attach before and after screenshots or videos of the change if applicable.

[fix] inverse joint order for ik solver

---

docs/source/roboverse_learn/imitation_learning/openvla.md
roboverse_learn/vla/rlds_utils/roboverse/CITATIONS.bib
roboverse_learn/vla/rlds_utils/roboverse/roboverse.py
roboverse_learn/vla/rlds_utils/visualize_dataset.py

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
List any dependencies that are required for this change.
Fixes # (issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update
Please describe how to test the change if applicable.
Please attach before and after screenshots or videos of the change if applicable.

[fix] rlds name for openVLA

---

roboverse_learn/vla/pi0/README.md
roboverse_learn/vla/pi0/convert_roboverse_to_lerobot.py
roboverse_learn/vla/pi0/roboverse_policy.py

- add scripts to convert roboverse demos to lerobot format
- add configs for finetuning on roboverse
- add a README file with step-by-step instructions

[add] pi0 on RoboVerse
