RoboVerseOrg/RoboVerse

roboverse_learn/eval_act.py, roboverse_learn/eval_rdt.py, roboverse_learn/eval_test_demo.py, roboverse_learn/train.py
There are some issues with the evaluation scripts (such as `eval_act.py`) in `roboverse_learn` caused by outdated usage of certain Metasim APIs.
1. The usage of `ScenarioCfg` and `env_class` in the script were incompatible with the current codebase. These references have been modified to align with the latest version.
2. When calling `env.handler.render()`, a `NotImplementedError` was raised. I have updated this to `env.handler.refresh_render()` to resolve the issue.
After making these changes, the evaluation scripts now run correctly.
=> Fix: Resolve the errors of using the evaluation scripts in roboverse_learn

docs/source/metasim/get_started/installation.rst
I wonder if cloning project is missing from installation in docs. That made `uv pip install -e ".[<simulator>]"` below a little confusing.
=> [docs/fix] Add clone project to installation.rst

metasim/sim/mujoco/mujoco.py
running command:
`python roboverse_learn/humanoidbench_rl/train_sb3.py --sim mujoco --num_envs 1 --robot=h1 --task humanoidbench:Stand`
error:
```
File "/home/panwei/RoboVerse/roboverse_learn/humanoidbench_rl/wrapper_sb3.py", line 
147, in step_wait
_, _, terminated_tensor, truncated_tensor, _ = self.env.step(action_dict)
File "/home/panwei/RoboVerse/metasim/sim/env_wrapper.py", line 88, in step
success = self.handler.checker.check(self.handler)
File "/home/panwei/RoboVerse/metasim/cfg/checkers/checkers.py", line 374, in check
states = handler.get_states()
File "/home/panwei/RoboVerse/metasim/sim/mujoco/mujoco.py", line 279, in get_states
state[object_type][obj.name]["dof_pos_target"] = {
File "/home/panwei/RoboVerse/metasim/sim/mujoco/mujoco.py", line 280, in <dictcomp>
joint_name: …
```
=> fix joint name extraction error in mujoco.py

get_started/0_static_scene.py, get_started/4_motion_planning.py, get_started/6_advanced_rendering.py, get_started/utils.py, metasim/cfg/checkers/checkers.py, metasim/cfg/checkers/detectors.py, metasim/data/quick_start/robots/franka/mjcf/panda.xml, metasim/scripts/collect_demo.py, metasim/scripts/replay_demo.py, metasim/sim/base.py, metasim/sim/env_wrapper.py, metasim/sim/genesis/genesis.py, metasim/sim/hybrid.py, metasim/sim/isaacgym/isaacgym.py, metasim/sim/isaaclab/env_overwriter.py, metasim/sim/isaaclab/isaaclab.py, metasim/sim/isaaclab/isaaclab_helper.py, metasim/sim/mujoco/mujoco.py, metasim/sim/pybullet/pybullet.py, metasim/sim/sapien/sapien2.py, metasim/sim/sapien/sapien3.py, metasim/utils/humanoid_robot_util.py, metasim/utils/save_util/save_util_v2.py, metasim/utils/state.py, roboverse_learn/humanoidbench_rl/wrapper_sb3.py
This PR changes state into tensorized representation to speed up for large scale parallel simulation
- Define new tensor states in `metasim/utils/state.py`
- including the body states
- Modify the `get_states()` method in isaaclab, isaacgym, mujoco, genesis, sanpien2/3, pybullet to return the tensor state
- isaaclab, isaacgym, mujoco support tensorized body states
- Modify scripts to fit tensorized state, including:
- `replay_demo.py` and `collect_demo.py`
- `get_started/*.py`
- `roboverse_learn/humanoidbench_rl/train_sb3.py`, all 3 training command for humanoidbench in [doc](https://roboverse.wiki/roboverse_learn/reinforcement_learning/humanoidbench_rl) is tested: 
```
python roboverse_learn/humanoidbench_rl/train_sb3.py --sim mujoco --num_envs 1 --robot=h1 --task humanoidbench:Stand
``` …
=> Tensorize states

metasim/cfg/scenario.py, metasim/cfg/sensors/__init__.py, metasim/cfg/sensors/base_sensor.py, metasim/cfg/sensors/contact.py, metasim/sim/base.py, metasim/sim/isaaclab/env_overwriter.py, metasim/sim/isaaclab/isaaclab.py, metasim/sim/isaaclab/isaaclab_helper.py, metasim/utils/state.py
This PR add contact force sensor cfg and can be supported by IsaacLab
Please test using
```
from __future__ import annotations
import logging
import os
import rootutils
from loguru import logger as log
from rich.logging import RichHandler
logging.addLevelName(5, "TRACE")
log.configure(handlers=[{"sink": RichHandler(), "format": "{message}"}])
rootutils.setup_root(__file__, pythonpath=True)
from metasim.cfg.scenario import ScenarioCfg
from metasim.cfg.sensors import ContactForceSensorCfg
from metasim.constants import SimType
from metasim.utils.demo_util import get_traj
from metasim.utils.setup_util import get_sim_env_class
def get_actions(all_actions, action_idx: int, num_envs: int):
envs_actions = all_actions[:num_envs]
actions = [
env_actions[action_idx] if action_idx < len(env_actions) …
```
=> infra: add contact force sensor cfg; isaaclab: support it

metasim/sim/isaaclab/isaaclab.py, metasim/sim/isaaclab/utils/ground_util.py, metasim/sim/isaaclab/utils/usd_util.py
This PR optimize the launching speed and VRAM consumption of isaaclab handler when no camera.
This PR is experimental and is continually updating.
- The launch time reduced from 6.5s to 3.75s
- The VRAM usage reduced from ~4GB to ~3GB
- The per step time remain the same: ~0.12s
Tested on RTX4060 + i7-14700F
Remove the default camera in `replay_demo.py` from 
```python
scenario = ScenarioCfg(
...
cameras=[camera],
...
)
```
to
```python
scenario = ScenarioCfg(
...
cameras=[],
...
)
```
And test using
```bash
LOGURU_LEVEL=TRACE python metasim/scripts/replay_demo.py --task=stack_cube --sim=isaaclab --num-envs=960 --headless
```
It is worth-noting that the test using IsaacGym handler with same setup:
```
python metasim/scripts/replay_demo.py --task=stack_cube --sim=isaacgym --num-envs=960 …
```
=> Optimize IsaacLab

metasim/cfg/sensors/cameras.py, metasim/sim/isaaclab/isaaclab.py, metasim/sim/isaaclab/isaaclab_helper.py, metasim/utils/state.py
This PR
- Extend the states for camera poses and intrinsics
- ensure IsaacLab handler support it
To test it, run the following file as `tmp.py`:
```bash
python tmp.py
```
```python
from __future__ import annotations
import logging
import os
try:
import isaacgym  # noqa: F401
except ImportError:
pass
import rootutils
import torch
from loguru import logger as log
from rich.logging import RichHandler
logging.addLevelName(5, "TRACE")
log.configure(handlers=[{"sink": RichHandler(), "format": "{message}"}])
rootutils.setup_root(__file__, pythonpath=True)
from metasim.cfg.scenario import ScenarioCfg
from metasim.cfg.sensors import PinholeCameraCfg
from metasim.constants import SimType
from metasim.utils.camera_util import get_cam_params
from metasim.utils.demo_util import get_traj
from …
```
=> add camera poses to states; isaaclab: support it

roboverse_learn/humanoidbench_rl/train_sb3.py
1. parralel training,  the type of var `done`  is  `np.array`, not single value.
2. it seem that we only need `wandb` when training? so i add training mode check for wandb initialization.
=> fix evaluation bug of humanoidbench

metasim/cfg/tasks/__init__.py, metasim/cfg/tasks/simpler_env/simpler_env_grasp_opened_coke_can_cfg.py, metasim/cfg/tasks/simpler_env/simpler_env_move_near.py, metasim/constants.py
Updated simpler env move near. Why the main branch contains an incomplete simpler env?
=> Simpler env move near

dashboard/minimal_test_script.py, docs/source/conf.py, metasim/scripts/collect_demo.py, metasim/scripts/empty_demo.py, metasim/scripts/motion_planning.py, metasim/scripts/motion_planning_gapartnet.py, metasim/scripts/random_action.py, metasim/scripts/random_action_ee.py, metasim/scripts/random_action_pure.py, metasim/scripts/random_action_really_pure.py, metasim/scripts/replay_demo.py, metasim/scripts/retarget_demo.py, metasim/scripts/teleop_keyboard.py, metasim/scripts/teleop_phone.py, metasim/scripts/train_ppo.py, metasim/scripts/train_ppo_vec.py, metasim/sim/genesis/genesis.py, metasim/test/state_consistency.py, pyproject.toml, scripts/convert_traj_v1_to_v2.py, scripts/statistics/main.py, scripts/test_usd.py
This PR remove dependency on `rootutils` package, and remove its import in `metasim` module, since we already use pip install for it. The `roboverse_learn` and `get_started` are still allowd to keep using `rootutils` since they may not be prepared as a python module
=> [refactor] remove rootutils 

metasim/sim/isaaclab/utils/custom_direct_rl_env.py
This PR align `direct_rl_env` with IsaacLab v1.4.1 version.
Though the misalignment didn't cause any known bug, it is still a better practice to keep the code up to date
=> align direct_rl_env with IsaacLab v1.4.1 version

docs/source/metasim/index.md, docs/source/metasim/user_guide/support_matrix.rst, metasim/cfg/simulator_params.py, metasim/cfg/tasks/humanoidbench/base_cfg.py, metasim/sim/genesis/genesis.py, metasim/sim/isaacgym/isaacgym.py, metasim/sim/isaaclab/empty_env.py, metasim/sim/isaaclab/isaaclab.py, metasim/sim/mujoco/mujoco.py, metasim/sim/pybullet/pybullet.py, metasim/sim/sapien/sapien3.py
This PR:
1. Add [support matrix](https://doc-support-matrix.roboverse-release.pages.dev/metasim/user_guide/support_matrix) to doc
2. Align isaaclab with recently added `sim_params` in #164 
3. Align `dt` across different simulators. Currently use their own default value in the original simulator by default. Not aligning them with a specific number is because MuJoCo has so much difference with other simulators. It seems MuJoCo must work with very high precision (dt=1/500) to work well
=> [doc] support matrix

docs/source/metasim/api/metasim/metasim.cfg.objects.rst, metasim/cfg/objects.py, metasim/cfg/tasks/calvin/scene/scene_A.py, metasim/cfg/tasks/calvin/scene/scene_B.py, metasim/cfg/tasks/calvin/scene/scene_C.py, metasim/cfg/tasks/calvin/scene/scene_D.py, metasim/sim/genesis/genesis.py, metasim/sim/isaacgym/isaacgym.py, metasim/sim/isaaclab/isaaclab.py, metasim/sim/isaaclab/isaaclab_helper.py, metasim/sim/mujoco/mujoco.py, metasim/sim/pybullet/pybullet.py, metasim/sim/sapien/sapien2.py, metasim/sim/sapien/sapien3.py, metasim/utils/configclass.py
This PR makes the following modifications:
1. reorganize `objects.py` using [mixin](https://en.wikipedia.org/wiki/Mixin) style;
- I personally think mixin style is better than the composition style utilized by IsaacLab, e.g. [RigidObjectCfg](https://isaac-sim.github.io/IsaacLab/main/source/api/lab/isaaclab.assets.html#isaaclab.assets.RigidObjectCfg). mixin style keeps everything at the same level and avoid nested access for an attribute. It also shorten the code length compared to composition style. Moreover, the usual weakness of mixin style -- hard to write unittest / debug -- is avoided, because all these classes serve only as configurations 
3. improve docstrings; 
4. fix `configclass` bug about inherited property; 
5. primitive object doesn't support scale
=> [refactor] reorganize `objects.py`

metasim/sim/mjx/mjx.py, metasim/sim/mjx/mjx_helper.py, metasim/sim/mujoco/mujoco.py
According to the official MuJoCo API docs and forum clarification, all c * spatial vectors store angular components first, then linear components
MuJoCo API reference → “c-frame variables” 
https://mujoco.readthedocs.io/en/stable/APIreference/APItypes.html#c-frame-variables
In RoboVerse we assume linear-then-angular ( vx vy vz wx wy wz ) for every velocity-like field exposed to agents.
The previous implementation in metasim/sim/mujoco.py and metasim/sim/mjx/mjx.py directly forwarded MuJoCo’s raw data.cvel, leading to a silent mismatch between:
=> [fix] mujoco&mjx cvel  bugs

metasim/sim/env_wrapper.py, metasim/sim/mujoco/mujoco.py
This PR fixes #98 
MuJoCo simulation uses `mj_step` in the gym wrapper instead of `mj_forward` to update derived quantities after modifying `qpos` and `qvel`. Using `mj_step` can introduce slight simulation discrepancies. Replacing it with `mj_forward` ensures that only the derived states are updated, resolving the inconsistency.
=> [fix] issue #98 on mujoco state inconsistency

metasim/sim/env_wrapper.py, metasim/sim/isaacgym/isaacgym.py
fix some bugs in `isaacgym` and `env_wrapper.py` reset pipeline
1. delete `simulate()` after every time reset && fix missing declaring `self._effort` in in isaacgym (it will raise error if we apply 1.)
2. fix passing device in when initializing  `_episode_length_buf` in env_wrapper
3. remove redudant for loop in `set_states`
=> [fix/isaacgym] reset pipeline 

metasim/sim/mjx/mjx.py
1.Adds support for configuring timestep directly via the ScenarioConfig.
2.Restricts rendering to single-environment mode for now, with a warning logged.
3.use JIT forward in set_states for acceleration.
All changes are tested locally.
=> Feature/set timestep and use JIT forward in set_state

metasim/sim/base.py, metasim/sim/genesis/genesis.py, metasim/sim/isaacgym/isaacgym.py, metasim/sim/isaaclab/isaaclab.py, metasim/sim/mjx/mjx.py, metasim/sim/mujoco/mujoco.py, metasim/sim/parallel.py, metasim/sim/pybullet/pybullet.py, metasim/sim/pyrep/pyrep.py, metasim/sim/sapien/sapien2.py, metasim/sim/sapien/sapien3.py
As title. every time `get_states()` is called, the states are cached, until the next `simulate()`
=> [performance] add caching for get_states method

metasim/sim/isaaclab/utils/usd_util.py
As title. This PR is a walkaround. Having no idea why autodownload could be buggy. Before this PR, the command
```
python metasim/scripts/replay_demo.py --task=stack_cube --random.scene
```
would cause the following error
```
2025-06-11 21:07:03 [11,790ms] [Error] [carb.graphics-vulkan.plugin] VkResult: ERROR_OUT_OF_HOST_MEMORY
2025-06-11 21:07:03 [11,790ms] [Error] [carb.graphics-vulkan.plugin] vkCreateFence failed.
```
It seems there are tricky problem is either isaaclab or python multiprocessing
=> [bugfix] isaaclab scene don't autodownload

metasim/utils/hf_util.py
1. autodownload use `hf_api.file_exists` instead of `hf_fs.exists` to speed up, as recommended in [hf doc](https://huggingface.co/docs/huggingface_hub/main/en/package_reference/hf_file_system#huggingface_hub.HfFileSystem.exists)
2. fix related comments
=> [refactor] autodownload use speed up

metasim/sim/isaaclab/isaaclab.py
Introduced in #240 
Running `get_started/1_control_robot.py` with the Isaaclab simulator results in a static video output — the robot does not appear to move or update correctly during the simulation.
Video reference:  
https://github.com/user-attachments/assets/20612a19-f6aa-4562-8b0a-fb243d2ab5c1
```bash
python get_started/1_control_robot.py --sim isaaclab
```
Call `self.simulate()` before `self.get_states()` in `metasim/sim/isaaclab/isaaclab.py`  to ensure `_state_cache_expire` is set to `True`. This guarantees that the correct observation is obtained from the simulator.
With the fix, the simulation runs as expected, showing the robot in motion.
Fixed result example:
https://github.com/user-attachments/assets/1e6f5df0-e660-40d3-8938-9293d4a9d590
=> [fix] call simulate before get_states

metasim/sim/isaacgym/isaacgym.py, metasim/sim/mjx/mjx.py, roboverse_learn/fast_td3/configs/isaacgym.yaml, roboverse_learn/fast_td3/configs/mjc.yaml, roboverse_learn/fast_td3/configs/mjx.yaml, roboverse_learn/fast_td3/configs/mjx_fast.yaml, roboverse_learn/fast_td3/configs/mjx_pg.yaml, roboverse_learn/fast_td3/train.py, roboverse_learn/fast_td3/wrapper.py, roboverse_learn/humanoidbench_rl/configs/isaacgym.yaml, roboverse_learn/humanoidbench_rl/configs/isaaclab.yaml, roboverse_learn/humanoidbench_rl/configs/mjx.yaml, roboverse_learn/humanoidbench_rl/configs/mujoco.yaml, roboverse_learn/humanoidbench_rl/train_sb3.py
This PR fixesthe RL infra bugs caused by multi-robots. The config files and wrappers for humanoidbench_rl and fast_td3 have been adjusted to account for this change. For now, only consider robots[0] in both environments to ensure training.
=> [fix] fix bugs for RL infra and configs caused by multirobots

metasim/cfg/tasks/humanoidbench/base_cfg.py, metasim/cfg/tasks/humanoidbench/crawl_cfg.py, metasim/cfg/tasks/humanoidbench/sit_cfg.py, metasim/cfg/tasks/humanoidbench/slide_cfg.py, metasim/cfg/tasks/humanoidbench/stair_cfg.py
Same problem mentioned in PR#295
When we ported HumanoidBench to RoboVerse, the original code called .mean() without dim, assuming a single-env tensor.
With batched tensors the call now collapses both the (x,y) velocity axis and the num_env axis, causing every environment to share one “dont move” reward term.
The patch specifies mean(dim=-1) so we only average the two lateral velocity components while keeping the batch dimension intact.
Each environment now receives an independent reward signal.
=> fix mean(dim=-1)

metasim/sim/isaacgym/isaacgym.py
Add checks for `gym.graphics` and `gym.render_all_camera_sensors` only when the camera list is not empty to avoid performance degradation.
=> [fix] isaacgym render camera checks

metasim/sim/mujoco/mujoco.py
title: all get-started script wasn't running on clusters due to an offscreen size error
=> [fix]: mujoco handler fix headless offscreen size error

metasim/sim/isaacgym/isaacgym.py, metasim/sim/mujoco/mujoco.py, roboverse_learn/tasks/base.py, roboverse_learn/tasks/test.py
As discussed with @charlietcheng @MurphyZhao04, we are now re-designing roboverse-learn architecture.
The first step is to design a base task class. 
Then rapidly we need to re-design cfg system and metasim APIs, which requires more discussions and development.
Our goal is to separate the simulation job of metasim apart from task-related jobs. This will allow easier repurposing of metasim as simply a simulator, easier task migration, and easier new task implementation.
To migrate a task, you just need to provide step(), reset(), observation_space(), action_space() methods in the same format of this base class.
To write your own task, you need to inherit this base class and override the following methods:
- _observation
- _privileged_observation
- _reward
- _terminated
- _time_out
- …
=> [dev] New architecture for roboverse tasks (ongoing)

metasim/cfg/randomization.py
When running basic replay demo script
```
python metasim/scripts/replay_demo.py --task=close_box --sim=mujoco       
```
I got error
```
/home/fs/miniforge3/envs/metasim/lib/python3.10/site-packages/tyro/_parsers.py:347: UserWarning: The field `random.friction.num-buckets` is annotated with type `<class 'int'>`, but the default value `<dataclasses._MISSING_TYPE object at 0x709339bbe5f0>` has type `<class 'dataclasses._MISSING_TYPE'>`. We'll try to handle this gracefully, but it may cause unexpected behavior.
warnings.warn(message)
/home/fs/miniforge3/envs/metasim/lib/python3.10/site-packages/tyro/_parsers.py:347: UserWarning: The field `random.friction.dist-fn` is annotated with type `typing.Callable`, but the default value `<dataclasses._MISSING_TYPE object at 0x709339bbda50>` has type …
```
=> [bugfix] scenario randomization cfg terms missing to none

.dockerignore, Dockerfile
This PR fixes a Docker build issue where the roboverse_pack directory was missing during the pip install step in the Dockerfile. The build was failing because the package structure referenced roboverse_pack but the directory wasn't being copied into the Docker image.
The fix includes:
- Adding roboverse_pack directory to the Dockerfile COPY commands
- Updating .dockerignore to ensure roboverse_pack is not ignored during the Docker build
- Creating the missing roboverse_pack/__init__.py file to make it a proper Python package
Fixes Docker build failures related to missing roboverse_pack module.
Type of change
How to test
1. Run docker build . to verify the Docker image builds successfully
2. Confirm that the pip install step no longer …
=> Fixes Dockerfile pip install step by adding roboverse_pack
